# CMake generated Testfile for 
# Source directory: /home/ehds/Programs/leveldb
# Build directory: /home/ehds/Programs/leveldb/bld
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/home/ehds/Programs/leveldb/bld/c_test")
add_test(fault_injection_test "/home/ehds/Programs/leveldb/bld/fault_injection_test")
add_test(issue178_test "/home/ehds/Programs/leveldb/bld/issue178_test")
add_test(issue200_test "/home/ehds/Programs/leveldb/bld/issue200_test")
add_test(issue320_test "/home/ehds/Programs/leveldb/bld/issue320_test")
add_test(env_test "/home/ehds/Programs/leveldb/bld/env_test")
add_test(status_test "/home/ehds/Programs/leveldb/bld/status_test")
add_test(no_destructor_test "/home/ehds/Programs/leveldb/bld/no_destructor_test")
add_test(autocompact_test "/home/ehds/Programs/leveldb/bld/autocompact_test")
add_test(corruption_test "/home/ehds/Programs/leveldb/bld/corruption_test")
add_test(db_test "/home/ehds/Programs/leveldb/bld/db_test")
add_test(dbformat_test "/home/ehds/Programs/leveldb/bld/dbformat_test")
add_test(filename_test "/home/ehds/Programs/leveldb/bld/filename_test")
add_test(log_test "/home/ehds/Programs/leveldb/bld/log_test")
add_test(recovery_test "/home/ehds/Programs/leveldb/bld/recovery_test")
add_test(skiplist_test "/home/ehds/Programs/leveldb/bld/skiplist_test")
add_test(version_edit_test "/home/ehds/Programs/leveldb/bld/version_edit_test")
add_test(version_set_test "/home/ehds/Programs/leveldb/bld/version_set_test")
add_test(write_batch_test "/home/ehds/Programs/leveldb/bld/write_batch_test")
add_test(memenv_test "/home/ehds/Programs/leveldb/bld/memenv_test")
add_test(filter_block_test "/home/ehds/Programs/leveldb/bld/filter_block_test")
add_test(table_test "/home/ehds/Programs/leveldb/bld/table_test")
add_test(arena_test "/home/ehds/Programs/leveldb/bld/arena_test")
add_test(bloom_test "/home/ehds/Programs/leveldb/bld/bloom_test")
add_test(cache_test "/home/ehds/Programs/leveldb/bld/cache_test")
add_test(coding_test "/home/ehds/Programs/leveldb/bld/coding_test")
add_test(crc32c_test "/home/ehds/Programs/leveldb/bld/crc32c_test")
add_test(hash_test "/home/ehds/Programs/leveldb/bld/hash_test")
add_test(logging_test "/home/ehds/Programs/leveldb/bld/logging_test")
add_test(env_posix_test "/home/ehds/Programs/leveldb/bld/env_posix_test")
